version: "3.8"

#======================================================================================================================
# Restart policy.
#======================================================================================================================
x-restart: &restart
  restart: unless-stopped

#======================================================================================================================
# Environment variables shared with each container.
#======================================================================================================================
x-common-env: &common
  TZ: ${TIMEZONE}

#======================================================================================================================
# Unbound environment variables.
#  - commented variables contain unbound's default values
#  - uncommented variables are my suggested overrides
# Remove section entirely to leave everything as default with DNSSEC disabled.
#======================================================================================================================
x-unbound-env: &unbound
  UNBOUND_ENABLE_DNSSEC: 1
  #UNBOUND_AGGRESSIVE_NSEC: yes
  #UNBOUND_CACHE_MAX_TTL: 86400
  UNBOUND_CACHE_MIN_TTL: 3600
  UNBOUND_DENY_ANY: yes
  #UNBOUND_DO_IP4: yes
  UNBOUND_DO_IP6: no
  #UNBOUND_DO_NOT_QUERY_LOCALHOST: yes
  #UNBOUND_DO_TCP: yes
  #UNBOUND_DO_UDP: yes
  #UNBOUND_EDNS_BUFFER_SIZE: 1232
  #UNBOUND_EXTENDED_STATISTICS: no
  UNBOUND_HARDEN_ALGO_DOWNGRADE: yes
  UNBOUND_HARDEN_BELOW_NXDOMAIN: yes
  UNBOUND_HARDEN_DNS_STRIPPED: yes
  #UNBOUND_HARDEN_GLUE: yes
  UNBOUND_HARDEN_LARGE_QUERIES: yes
  #UNBOUND_HARDEN_SHORT_BUFSIZE: yes
  UNBOUND_HIDE_HTTP_USER_AGENT: yes
  UNBOUND_HIDE_IDENTITY: yes
  UNBOUND_HIDE_VERSION: yes
  #UNBOUND_INCOMING_NUM_TCP: 10
  #UNBOUND_INTERFACE_AUTOMATIC: no
  #UNBOUND_MAX_UDP_SIZE: 4096
  #UNBOUND_MINIMAL_RESPONSES: yes
  #UNBOUND_NUM_THREADS: 1
  #UNBOUND_OUTGOING_NUM_TCP: 10
  #UNBOUND_PREFER_IP4: no
  #UNBOUND_PREFER_IP6: no
  UNBOUND_PREFETCH_KEY: yes
  UNBOUND_PREFETCH: yes
  UNBOUND_PRIVATE_ADDRESS_ENABLE: 1
  #UNBOUND_QNAME_MINIMISATION: yes
  #UNBOUND_SHM_ENABLE: no
  #UNBOUND_SHM_KEY: 11777
  #UNBOUND_SO_RCVBUF: 0
  #UNBOUND_SO_SNDBUF: 0
  #UNBOUND_STATISTICS_CUMULATIVE: no
  #UNBOUND_STATISTICS_INHIBIT_ZERO: yes
  #UNBOUND_STATISTICS_INTERVAL: 0
  UNBOUND_USE_CAPS_FOR_ID: yes
  #UNBOUND_VERBOSITY: 1

#======================================================================================================================
# Pi-hole environment variables.
#======================================================================================================================
x-pihole-env: &pihole
  PIHOLE_DNS_: unbound;unbound-backup
  VIRTUAL_HOST: ${PIHOLE_HOST_NAME}
  WEBPASSWORD: ${PIHOLE_ADMIN_PASSWORD}

#======================================================================================================================
# Proxy server environment variables.
#======================================================================================================================
x-proxy-env: &proxy
  PROXY_AUTO_PRIMARY: ${PIHOLE_DOMAIN}
  PROXY_AUTO_UPSTREAM: http://pihole
  PROXY_DOMAIN: ${PROXY_DOMAIN}
  PROXY_LETS_ENCRYPT_EMAIL: ${PROXY_LETS_ENCRYPT_EMAIL}
  PROXY_LETS_ENCRYPT_LIVE: ${PROXY_LETS_ENCRYPT_LIVE}

#======================================================================================================================
# Services definition.
#======================================================================================================================
services:
  unbound:
    image: bfren/unbound:latest
    container_name: unbound
    <<: *restart
    environment:
      <<: [*common, *unbound]
    networks:
      dns:
        ipv4_address: ${IP_RANGE}.2

  unbound-backup:
    image: bfren/unbound:${UNBOUND_PIN} # suggest updating this pinned version manually after each release
    container_name: unbound-backup
    <<: *restart
    environment:
      <<: [*common, *unbound]
    networks:
      dns:
        ipv4_address: ${IP_RANGE}.200

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    depends_on:
      - unbound
      - unbound-backup
    <<: *restart
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      <<: [*common, *pihole]
    volumes:
      - ./v/pihole:/etc/pihole
      - ./v/dnsmasq:/etc/dnsmasq.d
    networks:
      dns:
        ipv4_address: ${IP_RANGE}.3

  proxy:
    image: bfren/nginx-proxy:7
    container_name: proxy
    depends_on:
      - pihole
    <<: *restart
    ports:
      - "80:80"
      - "443:443"
    environment:
      <<: [*common, *proxy]
    volumes:
      - ./v/sites:/sites
      - ./v/ssl:/ssl
    networks:
      dns:
        ipv4_address: ${IP_RANGE}.4

networks:
  dns:
    name: dns
    ipam:
      driver: default
      config:
        - subnet: ${IP_RANGE}.0/16
