#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

bf-env "UNBOUND_CONF" "/etc/unbound/unbound.conf"

if [ "${UNBOUND_ENABLE_DNSSEC:-}" = "1" ] ; then
    bf-env "UNBOUND_ROOT_HINTS" "/etc/unbound/root.hints"
    bf-env "UNBOUND_ROOT_KEY" "/etc/unbound/root.key"
fi

bf-env "UNBOUND_LIB" "${BF_LIB}/unbound"
