#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

bf-env "UNBOUND_CONF" "/etc/unbound/unbound.conf"
bf-env "UNBOUND_TRUSTED_KEY" "/etc/unbound/root.key"
bf-env "UNBOUND_LIB" "${BF_LIB}/unbound"
