#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate Unbound config file.
#======================================================================================================================

bf-esh \
    ${BF_TEMPLATES}/unbound.conf.esh \
    ${UNBOUND_CONF}

bf-ch-apply "${BF_CH_D}/10-unbound"
