#!/command/with-contenv sh


#======================================================================================================================
# Update root anchor.
#======================================================================================================================

if [ "${UNBOUND_ENABLE_DNSSEC:-}" = "1" ] ; then
    unbound-anchor -v -a ${UNBOUND_ROOT_KEY}
else
    bf-notok "DNSSEC is disabled."
fi
